apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: uber-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: uber
    spec:
      containers:
      - name: uber-demo
        image: prasanna025153/uber-cold-fusion:kube
        ports:
          - containerPort: 7000
        env:
          - name: UBER_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: uber-secret
                key: UBER_CLIENT_ID
          - name: UBER_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: uber-secret
                key: UBER_CLIENT_SECRET
